"""empty message

Revision ID: 8c7b7fe6a3ac
Revises: 
Create Date: 2022-01-16 16:00:09.718974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c7b7fe6a3ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('text', sa.String(length=500), nullable=True),
    sa.Column('owner', sa.String(length=64), nullable=True),
    sa.Column('date_create', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ads_owner'), 'ads', ['owner'], unique=False)
    op.create_index(op.f('ix_ads_text'), 'ads', ['text'], unique=False)
    op.create_index(op.f('ix_ads_title'), 'ads', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ads_title'), table_name='ads')
    op.drop_index(op.f('ix_ads_text'), table_name='ads')
    op.drop_index(op.f('ix_ads_owner'), table_name='ads')
    op.drop_table('ads')
    # ### end Alembic commands ###
